# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CustomCamera' do
   use_frameworks!

  # Pods for CustomCamera

  target 'CustomCameraTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Masonry'
  end

  target 'CustomCameraUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
